baseURL = 'https://hashed-io.github.io/hashed.network'
languageCode = 'en-us'

[params]
  title = 'Hashed Network Coming Soon'
  titleSeparator = "|"
  description = "Hashed Netwok is Polkadot's hub for businesses looking to leverage web3 and digitally-native organizations."
  thumbnail = "logo/logo.jpg"